FROM       docker.io/centos:7

RUN        yum -y update
RUN        yum -y install wget java-1.8.0-openjdk.x86_64

RUN        wget http://apache.tt.co.kr/kafka/2.4.0/kafka_2.12-2.4.0.tgz
RUN        tar xvzf kafka_2.12-2.4.0.tgz

EXPOSE     2181
EXPOSE     2888
EXPOSE     3888
EXPOSE     9092

WORKDIR    /kafka_2.12-2.4.0
ENTRYPOINT ["./bin/kafka-server-start.sh"]
CMD        ["./config/server.properties"]
