FROM  docker.io/centos:7

RUN   yum -y update
RUN   yum -y install wget java-1.8.0-openjdk.x86_64

RUN   wget http://apache.tt.co.kr/kafka/2.4.0/kafka_2.12-2.4.0.tgz
RUN   tar xvzf kafka_2.12-2.4.0.tgz
RUN   rm kafka_2.12-2.4.0.tgz
